---
name-template: "Release $NEXT_PATCH_VERSION"
tag-template: "{{date 'YYYY.M'}}.0"
version-template: "{{date 'YYYY.M'}}.0"

categories:
  - title: "🚨 Breaking Changes"
    labels:
      - "breaking-change"
      - "major"
  - title: "🚀 New Features"
    labels:
      - "new-feature"
      - "minor"
  - title: "🐛 Bug Fixes"
    labels:
      - "bugfix"
      - "security"
  - title: "📈 Performance Improvements"
    labels:
      - "performance"
  - title: "🧹 Refactorings"
    labels:
      - "refactor"
  - title: "📝 Documentation"
    labels:
      - "documentation"
  - title: "🛠 Maintenance"
    labels:
      - "maintenance"
      - "ci"
      - "dependencies"
  - title: "📦 Other Changes"
    labels:
      - "enhancement"

change-template: "- $TITLE (#$NUMBER)"
