---
tag-prefix: "v"
style: simple

version-resolver:
  major:
    labels: ["breaking-change", "major"]
  minor:
    labels: ["new-feature", "minor"]
  patch:
    labels:
      - "bugfix"
      - "security"
      - "performance"
      - "refactor"
      - "documentation"
      - "maintenance"
      - "ci"
      - "dependencies"
      - "enhancement"
  default: patch

tag-template: "v$RESOLVED_VERSION"
name-template: "v$RESOLVED_VERSION"

sort-by: merged_at
sort-direction: descending
prerelease: false
include-pre-releases: false
latest: "true"
filter-by-commitish: false
pull-request-limit: 5
categories:
  - title: "🚨 Breaking changes"
    labels: ["breaking-change", "major"]
  - title: "✨ New features"
    labels: ["new-feature", "minor"]
  - title: "🐛 Bug fixes"
    labels: ["bugfix"]
  - title: "🚀 Enhancements"
    labels: ["enhancement", "refactor", "performance"]
  - title: "🧰 Maintenance"
    labels: ["maintenance", "ci", "security"]
  - title: "📚 Documentation"
    labels: ["documentation"]
  - title: "⬆️ Dependency updates"
    labels: ["dependencies"]
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

template: |
  ## What’s Changed
  $CHANGES
