---
name-template: "$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚨 Breaking changes"
    labels: ["breaking-change", "major"]
  - title: "✨ New features"
    labels: ["new-feature", "minor"]
  - title: "🐛 Bug fixes"
    labels: ["bugfix"]
  - title: "🚀 Enhancements"
    labels: ["enhancement", "refactor", "performance"]
  - title: "🧰 Maintenance"
    labels: ["maintenance", "ci", "security"]
  - title: "📚 Documentation"
    labels: ["documentation"]
  - title: "⬆️ Dependency updates"
    labels: ["dependencies"]
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "breaking-change"
      - "major"
  minor:
    labels:
      - "new-feature"
      - "minor"
  patch:
    labels:
      - "bugfix"
      - "enhancement"
      - "refactor"
      - "performance"
      - "maintenance"
      - "ci"
      - "documentation"
      - "dependencies"
      - "security"
  default: patch

template: |
  ## What’s Changed
  $CHANGES
