---
template: |
  $CHANGES

version-resolver:
  major:
    labels: ["breaking-change", "major"]
  minor:
    labels: ["new-feature", "minor"]
  patch:
    labels:
      [
        "bugfix",
        "security",
        "performance",
        "refactor",
        "documentation",
        "maintenance",
        "ci",
        "dependencies",
        "enhancement",
      ]
  default: patch

tag-prefix: "v"
tag-template: "v$NEXT_PATCH_VERSION"
name-template: "Release $NEXT_PATCH_VERSION"

change-template: "- $TITLE (#$NUMBER)"
no-changes-template: "* No changes"

categories:
  - title: "🚨 Breaking Changes"
    labels: ["breaking-change", "major"]
  - title: "🚀 New Features"
    labels: ["new-feature", "minor"]
  - title: "🐛 Bug Fixes"
    labels: ["bugfix", "security"]
  - title: "📈 Performance Improvements"
    labels: ["performance"]
  - title: "🧹 Refactorings"
    labels: ["refactor"]
  - title: "📝 Documentation"
    labels: ["documentation"]
  - title: "🛠 Maintenance"
    labels: ["maintenance", "ci", "dependencies"]
  - title: "📦 Other Changes"
    labels: ["enhancement"]

sort-by: merged_at
sort-direction: descending
prerelease: false
include-pre-releases: false
latest: "true"
filter-by-commitish: false
pull-request-limit: 5
category-template: "## $TITLE"
header: ""
footer: ""
