[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"

[project]
name = "aioautomower"
# The version is set by GH action on release
version = "0.0.0"
description = "MPython module to talk to Husqvarna Automower."
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICENSE"]

authors = [
  { name = "Thomas Peter Protzner", email = "thomas.protzner@gmail.com" },
]

keywords = ["Husqvarna", "Automower", "api", "async", "client"]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Framework :: AsyncIO",
  "Intended Audience :: Developers",
  "Natural Language :: English",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
  "aiohttp>=3.9.3,<4",
  "ical>=8.0.1",
  "mashumaro>=3.12,<4",
  "orjson>=3.11.2,<4",
  "PyJWT>=2.8.0,<3",
  "python-dateutil>=2.9.0.post0,<3",
  "tzlocal>=5.2,<6",
]

[project.urls]
Homepage = "https://github.com/Thomas55555/aioautomower"
Repository = "https://github.com/Thomas55555/aioautomower"
Documentation = "https://github.com/Thomas55555/aioautomower"
Issues = "https://github.com/Thomas55555/aioautomower/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/aioautomower"]

[dependency-groups]
dev = [
  "aiointercept==0.1.9",
  "codespell==2.4.3",
  "covdefaults==2.3.0",
  "coverage[toml]==7.16.0",
  "prek==0.4.14",
  "pre-commit-hooks==6.0.0",
  "pytest==9.1.1",
  "pytest-asyncio==1.4.0",
  "pytest-codspeed==5.0.3",
  "pytest-cov==7.1.0",
  "ruff==0.16.5",
  "syrupy==6.0.0",
  "time-machine==3.5.0",
  "ty==0.0.74",
  "yamllint==1.38.0",
]

[tool.pytest.ini_options]
addopts = "--cov=aioautomower --cov-report=term-missing -vv"
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"

[tool.ruff]
fix = true
show-fixes = true
src = ["./src"]
target-version = "py311"
line-length = 88
include = ["src/**/*.py", "tests/**/*.py"]

[tool.ruff.lint]
ignore = [
  "ANN401", # Opinioated warning on disallowing dynamically typed expressions
  "D203", # Conflicts with other rules
  "D213", # Conflicts with other rules
  "D417", # False positives in some occasions
  "PLR2004", # Just annoying, not really useful
  "CPY001",  # Just annoying, not really useful
  # Conflicts with the Ruff formatter
  "COM812",
]
select = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"example.py" = ["T201", "T203"] # Allow for main entry & scripts to write to stdout
"tests/**/*.py" = [
    "SLF001", #access to private members
    "S101", # asserts allowed in tests...
    "ARG", # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT", # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    "PLR2004", # Magic value used in comparison, ...
    "S311", # Standard pseudo-random generators are not suitable for cryptographic purposes
    "S105", # needed in tests (hardcoded password)
]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true
suppress-dummy-args = true

[tool.ruff.lint.flake8-builtins]
builtins-ignorelist = ["id"]

[tool.ruff.lint.pydocstyle]
# Use Google-style docstrings.
convention = "pep257"

[tool.ruff.lint.pylint]
max-branches=25
max-returns=15
max-args=10
max-statements=50

[tool.ty.environment]
python-version = "3.11"
root = ["./src"]

[tool.ty.rules]
missing-type-argument = "error"
possibly-unresolved-reference = "warn"

[tool.coverage.report]
show_missing = true
fail_under = 50

[tool.coverage.run]
plugins = ["covdefaults"]
source = ["aioautomower"]
