"""Models for inputs from the Autcomower Connect API."""

from .model_event import (
    CuttingHeightAttributes,
    GenericEventData,
    HeadLightAttributes,
    PositionAttributes,
)
from .model_rest import (
    MowerDataAttributes,
    MowerDataItem,
    MowerDataResponse,
)

__all__ = [
    "JWT",
    "WEEKDAYS",
    "WEEKDAYS_TO_ICAL",
    "Actions",
    "AutomowerCalendarEvent",
    "Battery",
    "Calendar",
    "Capabilities",
    "ConvertScheduleToCalendar",
    "CuttingHeightAttributes",
    "DurationSerializationStrategy",
    "ExternalReasons",
    "GenericEventData",
    "HeadLightAttributes",
    "Headlight",
    "HeadlightModes",
    "InactiveReasons",
    "Metadata",
    "Mower",
    "MowerActivities",
    "MowerAttributes",
    "MowerData",
    "MowerDataAttributes",
    "MowerDataItem",
    "MowerDataResponse",
    "MowerList",
    "MowerModes",
    "MowerStates",
    "Override",
    "Planner",
    "PositionAttributes",
    "Positions",
    "RestrictedReasons",
    "Settings",
    "Statistics",
    "StayOutZones",
    "System",
    "Tasks",
    "TimeSerializationStrategy",
    "User",
    "WorkArea",
    "Zone",
    "convert_timestamp_to_aware_datetime",
    "error_key_dict",
    "error_key_list",
    "generate_work_area_dict",
    "generate_work_area_names_list",
    "get_work_area_name",
    "make_name_string",
]
