---
name: CodSpeed

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.11"

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v7.0.1
      - name: 🏗 Set up uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: 🏗 Install dependencies
        run: uv sync --locked
      - name: Run benchmarks
        uses: CodSpeedHQ/action@v5.0.3
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          mode: "instrumentation"
          run: uv run pytest tests/ --codspeed
