---
name: Lockfile

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lockfile:
    name: uv lockfile
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v7.0.1
      - name: 🏗 Set up uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true
          python-version: "3.11"
      - name: 🔍 Check lockfile
        run: uv lock --check
