---
name: "Validation And Formatting"
# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Download repo
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: "3.12"
