name: "Validation And Formatting"
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Download repo
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        name: Setup Python
        with:
          python-version: '3.11'
